import { vehicleLineEn, type CarsPageUi } from "./carsPageUiTypes";

export const carsPageUiZh: CarsPageUi = {
  heroKicker: "NHTSA 安全查询",
  heroTitle: "车辆召回",
  heroSub:
    "解码 VIN 或输入年款、品牌、车型以查看开放活动。打开活动可查看完整页面；切换语言即可按需翻译。",
  labelVin: "VIN",
  placeholderVin: "17 位 VIN",
  vinHint: "点击输入框或开始输入，从本设备上曾搜索过的 VIN 中选择。",
  dividerOr: "或 年款 / 品牌 / 车型",
  labelYear: "年款",
  labelMake: "品牌",
  labelModel: "车型",
  placeholderYear: "例如 2019",
  placeholderMake: "例如 Honda",
  placeholderModel: "例如 Civic",
  searchButton: "搜索召回",
  searchButtonSearching: "搜索中…",
  errorNeedVinOrYmm: "请输入 VIN，或年款、品牌与车型。",
  errorSearchFailed: "搜索失败",
  vinNoRecalls: (vin) => `未找到 VIN ${vin} 的相关召回。`,
  vinLookupNotFound: (vin) =>
    `未找到此 VIN ${vin} 的相关召回。请稍后再试。`,
  emptyNoRecalls: "NHTSA 数据中未报告此车辆有活跃召回。",
  badgeOpenCampaign: "开放活动 · NHTSA",
  cardViewDetails: "查看完整详情",
  translating: "翻译中…",
  campaignId: "活动编号",
  blockConsequence: "后果",
  blockSummary: "摘要",
  blockRemedy: "补救措施",
  blockComponent: "部件",
  openRecallsFor: (y, m, mo) => `年份 ${y} · 品牌 ${m} · 车型 ${mo}`,
  openRecallsForEn: vehicleLineEn,
  metaNoCampaigns: "无开放活动",
  metaNoCampaignsEn: "No open campaigns",
  metaCampaigns: (n) => (n === 1 ? "1 项活动" : `${n} 项活动`),
  metaCampaignsEn: (n) => `${n} campaign${n === 1 ? "" : "s"}`,
  pillReport: (d) => `报告 ${d}`,
};
